GET https://sureplugapi.onrender.com/users/getusers
Content-type: application/json

#########################################
https://sureplugapi.onrender.com/users/getusers
#######################

GET https://sureplugapi.onrender.com/users/single/642e82e5e0fc6d546bee22534


##############################################

POST https://sureplugapi.onrender.com/users/register
Content-type: application/json

{
    "name": "Samuel John",
    "email": "jethyjay330ko@gmail.com",
    "address": "No. 354 U/Zawu, Gonin Gora",
    "gsm": "08084343318",
    "state": "Kaduna",
    "lga": "Chikun",
    "skill": "Shoe Making",
    "businessName": "Jedi Shoes",
    "link": "jay.com",
    "images": "link"
}


##############################################

POST https://sureplugapi.onrender.com/users/login
Content-type: application/json

{
    "email": "jethyjay@gmail.com",
    "password": "123456"
}


##############################################

PATCH  https://sureplugapi.onrender.com/users/update/642e82e5e0fc6da5bce22534
Content-type: application/json

{
    "address": "Kawo"
}

##############################################

PATCH https://sureplugapi.onrender.com/users/status/642e82e5e0fc6da5bce22534


##############################################

DELETE https://sureplugapi.onrender.com/users/delete/642ec53e2f739a034041da9a



##############################################

POST https://sureplugapi.onrender.com/admin/create
Content-type: application/json

{
    "username": "admin",
    "password": "admin" 
}

##############################################

POST https://sureplugapi.onrender.com/admin/login
Content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

##############################################

POST https://sureplugapi.onrender.com/admin/create-skills
Content-type: application/json

{
    "name": "Barber"
}

##############################################

GET https://sureplugapi.onrender.com/admin/getskills
Content-type: application/json

##############################################

PATCH https://sureplugapi.onrender.com/admin/updateskill/64316d4cf86751f6adfa068a
Content-type: application/json

{
    "name": "Electrician"
}

##########################

POST https://sureplugapi.onrender.com/admin/search
Content-type: application/json

{
    "skill": "Shoe Making",
    "state": "Kaduna"
}


##########################

GET https://sureplugapi.onrender.com/admin/getsearch
Content-type: application/json





